spring.application.name=settlement-service


#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create-drop
#.kafka.bootstrap-servers=localhost:9092



# Database
# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/expense_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:rr}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rr123}
spring.datasource.hikari.maximum-pool-size=10

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=settlement-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Server
server.port=8082